### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by AhmadALBarqawi** [secml-lab-vt/EvolvingThreat-DeepfakeImageDetect#1]
When do you plan on releasing the dataset used in the paper?

**Comment by SifatMd** [comment]
Please fill up this [Google form](https://docs.google.com/forms/d/e/1FAIpQLSdOF6O7E-2U0q3_ISE5_NcPYg5sCFi_Q0szMf2QNrrF1HoQ-Q/viewform) to access our datasets and model checkpoints.
